name = "lightrag-nuxt"
compatibility_date = "2024-11-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"
publish = ".output/public"

[pages]
build_output_directory = ".output/public"
pages_build_output_dir = ".output/public"

[env.production]
name = "lightrag-nuxt"
workers_dev = true

[vars]
NUXT_PUBLIC_CF_WORKER_URL = "https://kv-vector-store.aiproductguy.workers.dev"
NUXT_PUBLIC_CF_ACCOUNT_ID = "f26bd04ac74daa191040b61d811d2a2c"

# Note: NUXT_CF_API_TOKEN should be set as a secret in the Cloudflare dashboard
  